#!/bin/sh

set -e

case "$1" in
    configure)
	update-alternatives --quiet --install /usr/bin/cc cc /usr/bin/tcc 10 \
       --slave /usr/share/man/man1/cc.1.gz cc.1.gz                           \
       /usr/share/man/man1/tcc.1.gz;
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#

exit 0
